//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. HEY IM NOT A TOOL!
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;


public class Unit : MonoBehaviour{

	public int hp;
	public int hp_max;
	public int dmg;
	public int speed;
	public int atkspeed;


	public Unit(){


	}

	void Start(){

	}


	void Update(){
		print ("am teh humen");
	}

	void attack(Unit target){
		//functionality breh
	}

	void generate(){

	}
}

