//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. HEY IM NOT A TOOL!
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections;
using UnityEngine;


public class Unit{

	public int hp;
	public int hp_max;
	public int dmg;
	public int speed;
	public int atkspeed;
	public Unit sl;
	public GameObject unit;
	
	public Unit (){
		sl = this;
		generate ();
	}

	public Unit(Unit SL){
		sl = SL;
		generate ();
		if (sl == null) {
			sl = this;
		}

	}


	void attack(Unit target){
		//functionality breh
	}

	void generate(){
		this.hp_max = Random.Range (8, 14);
		this.hp = this.hp_max;
		this.dmg = Random.Range (2, 4);
		this.speed = Random.Range (1, 5);
		this.atkspeed = Random.Range (1, 3);
	}
}

